spring.application.name=bot

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/alfred
spring.datasource.username=alfred
spring.datasource.password=alfred-api
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Logging
logging.level.com.alfred.bot=DEBUG
logging.level.org.springframework.web=INFO

#Waha
waha.api.key=alfred-secret-key
waha.dashboard.username=admin
waha.dashboard.password=admin
whatsapp.swagger.username=admin
whatsapp.swagger.password=admin

spring.flyway.enabled=false